### PR TITLE
remove fltk dependency for crossfm's example

### PR DESCRIPTION
**Pull request by hlolli**
not sure if this is the best example of an example, but I feel it's important to start removing unnecessary fltk useage within the manual.

### CODE REVIEW

**Comment by fggp** [comment]
I'm the author of this example and I like it.it still runs under Linux... I prefer to keep it and add a second example running without fltk... I'll do it ASAP

François

**Comment by tgrey1** [comment]
As per https://github.com/csound/csound/issues/1325 FLTK can not and will not be supported on OSX anymore.

I'm of the opinion that if FLTK examples are kept in the manual, they should be secondary examples, with the primary examples being platform agnostic and not relying on third party libraries or frontends (csoundqt, cabbage, fltk, etc)

**Comment by gogins** [comment]
I agree with tgrey1, the FLTK examples are worth keeping but a non-FLTK
example should come first (this is especially relevant to my online manual
with WebAssembly that runs examples in the browser and can't use FLTK).

Regards,
Mike

-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by fggp** [comment]
Finally, I replaced the example with another one which does not use FLTK.

**Pull request closed without merging**
