### PR TITLE
scanned info + tigoto

### PR DESCRIPTION
**Pull request by tjingboem**

### CODE REVIEW

**Comment by csounder** [comment]
tigoto is nice, clear, and nice sounding too!  the scanned explanations of the matix files is also very clear.  thanks!

**Comment by csounder** [comment]
Nice.  Nice sounding.  And I appreciate the further clarification of the
scanned matrix types and format

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Comment by tjingboem** [comment]
ah, thanks for confirming all is clear and understandable.

**Comment by csounder** [comment]
It is really great - flows brilliantly and clearly

*- Dr.B*


*Dr. Richard Boulanger*

Professor

Electronic Production and Design

*Berklee College of Music*

Professional Writing & Technology Division

**Pull request merged**
