### PR TITLE
different contributions

### PR DESCRIPTION
**Pull request by joachimheintz**
mainly new images for window functions

### CODE REVIEW

**Comment by jpffitch** [comment]
I am not sure I understand why the classical use of f statements in the score has been removed for orc statements.  That need some justification.

Sees to fail on Windows because of python2 v python3
h

**Comment by jpffitch** [comment]
Why the insertion of a tab into the line on taninv2?  Current line looks correct to me.

**Comment by joachimheintz** [comment]
yes actually i wanted to keep the current line.  i removed it because 
taninv2 was not in the list; perhaps than a typo when trying to re-insert.

**Comment by joachimheintz** [comment]
i think the usage of ftgen is now preferred against the usage of 
f-statements in the score.
in any case, i think it is good to have not only examples with 
f-statements on manual pages like this.

**Comment by jpffitch** [comment]
image7.png lookslike a rectangular window rather than Kaiser

**Comment by joachimheintz** [comment]
this is the reason i made three examples for kaiser: default (which is 
probably alpha=0), alpha=5 and alpha=10.  the manual states on 
https://csound.com/docs/manual/GEN20.html:

"The extra argument specifies how "open" the window is, for example a 
value of 0 results in a rectangular window and a value of 10 in a 
Hamming like window. "

**Comment by jpffitch** [comment]
OK it just looked unexpected.

**Pull request merged**
