### PR TITLE
Use Pygments for syntax highlighting

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request uses [Pygments](http://pygments.org) to perform syntax highlighting in [csd2docbook.py](https://github.com/csound/manual/blob/master/csd2docbook.py). (Full disclosure: I wrote the [Csound lexers](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/csound.py) used in Pygments.) This improves syntax highlighting, for example:

* [`expcurve` before](https://csound.github.io/docs/manual/expcurve.html) and [after](https://dl.dropboxusercontent.com/u/21723817/pygments-expcurve.html)
* [`pconvolve` before](https://csound.github.io/docs/manual/pconvolve.html) and [after](https://dl.dropboxusercontent.com/u/21723817/pygments-pconvolve.html)
* [`lua_opdef` before](https://csound.github.io/docs/manual/lua_opdef.html) and [after](https://dl.dropboxusercontent.com/u/21723817/pygments-luamoog.html)

This pull request also:

* Deletes the [examples-xml folder](https://github.com/csound/manual/tree/master/examples-xml) in favor of generating that as a build step.
* Has a largely rewritten README.md.
* Does _not_ include a [function for writing playable examples in csd2docbook.py](https://github.com/csound/manual/blob/master/csd2docbook.py#L236); such a function doesn’t seem to belong in a script named csd2docbook, but that could easily be added back in a separate script.

One issue I’m anticipating is that the [list of opcodes Pygments uses](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/lexers/_csound_builtins.py) is currently not as comprehensive as what was in [opcode_list.txt](https://github.com/csound/manual/blob/master/opcode_list.txt) (but it’ll be updated eventually). Hopefully the syntax highlighting improvements are enough to make this not a big deal.

### CODE REVIEW

**Comment by kunstmusik** [comment]
Not sure if I missed something, but I checked that pygments was installed and tried the latest from the PR. It looks like the generated HTML output doesn't have any highlighting in the examples. Ran "easy_install pygments", then ran "make html-dist".

**Comment by nwhetsell** [comment]
I didn’t notice that the `html` target copies CSS files to the html folder; [syntax-highlighting.css](https://github.com/nwhetsell/manual/blob/master/syntax-highlighting.css) wasn’t being copied. This is fixed in commit ec3c433fd5a095bbfb2472f22f41e57938adbfc9. If you want to see the syntax highlighting without rebuilding all the HTML files, just copy syntax-highlighting.css into the html folder (and refresh your browser).

pconvolve

**Comment by kunstmusik** [comment]
That's now working for me. I do find the style a bit muted a little odd that the types of vars are highlighted (e.g. the i in ivar, or k in kvar).  That said, overall I'm for the change.  It would be good to get reviews by @fsateler, @vlazzarini, @jpffitch, and @joachimheintz .

**Comment by jpffitch** [comment]
What problem is this supposed to solve?⁣

**Comment by fsateler** [comment]
> One issue I’m anticipating is that the list of opcodes Pygments uses is currently not as comprehensive as what was in opcode_list.txt (but it’ll be updated eventually).

Would it be possible to inject the opcode list into pygments?

**Comment by fsateler** [comment]
This appears to make generating the formatted csd part of the build, that looks like a nice improvement to me.

Also I like how strings are correctly parsed now.

**Comment by jpffitch** [comment]
A quick partial response-- I did not see any difference between the k and the var until I looked very closely.  The colours are just wrong to a colour blind reader
Old system did not have this⁣

**Comment by nwhetsell** [comment]
@jpffitch Please look at the before-and-after examples I linked to, and you will see several issues with the current syntax highlighter:

* Strings aren’t highlighted at all. You can see this in the double-quoted string in [`expcurve`](https://csound.github.io/docs/manual/expcurve.html). `out` is incorrectly highlighted as an opcode. This also holds true for braced strings `{{ }}`.

* Block comments aren’t highlighted. You can see this in [`lua_opdef`](https://csound.github.io/docs/manual/lua_opdef.html).

* User-defined opcodes aren’t highlighted very well, and their types may not be highlighted correctly. See [here](https://csound.github.io/docs/manual/opcode.html).

Pygments has numerous other advantages, not least of all is that it can highlight many languages, which comes in handy for highlighting something like the [`lua_opdef`](https://csound.github.io/docs/manual/lua_opdef.html) example.

**Comment by nwhetsell** [comment]
> Would it be possible to inject the opcode list into pygments?

@fsateler We could either

* Update [my fork of Pygments](https://bitbucket.org/nwhetsell/pygments-main) with more opcodes, and use that. I can make sure it all works on Travis CI, but this would make [Mercurial](https://www.mercurial-scm.org) a requirement of building the manual.

* Somehow patch Pygments after it’s installed.

I’m open to other suggestions.

**Comment by jpffitch** [comment]
More comments; looking at the attached example the variables are bold but 
the opcodes are not highlighted at all. Seems backwards to me.

Colour for r-vars suggests they are uniportant

Strings not distinguished

I must be seeing someting different to everyone else, but looks very 
retrograde to me in the manual

**Comment by nwhetsell** [comment]
@jpffitch The colors are from [Pygments’ lovelace style](https://bitbucket.org/birkenfeld/pygments-main/src/default/pygments/styles/lovelace.py). Since `k` is a type sigil, Pygments lexes it as a type, so it gets the color for types, which in lovelace happens to be a shade of blue. The colors applied to HTML pages are [here](https://github.com/nwhetsell/manual/blob/master/syntax-highlighting.css), for PDFs [here](https://github.com/nwhetsell/manual/blob/master/xsl/customPDF.xsl.in).

**Comment by nwhetsell** [comment]
@jpffitch Which example? In [syntax-highlighting.css](https://github.com/nwhetsell/manual/blob/master/syntax-highlighting.css), which provides the colors and styles for code:

* No code is bold.
* Opcodes get the color for `Name.Builtin` tokens (a shade of green).
* Strings get the color of `Literal.String.Double` tokens (a shade of red).

**Comment by fsateler** [comment]
@nwhetsell wouldn't it be possible to `pygments.lexers._csound_builtins.OPCODES = load_opcodes_list()` or something equivalent?

**Comment by jpffitch** [comment]
On Mon, 16 Jan 2017, Nate Whetsell wrote:

> 
> @jpffitch The colors are from Pygments’ lovelace style. Since k is a type
> sigil, Pygments lexes it as a type, so it gets the color for types, which in
> lovelace happens to be a shade of blue. The colors applied to HTML pages are
> here, for PDFs here.
>

Then whoever designed them is hostile to the colour blind.  For me not 
being to select usable colours is a huge backward step.  I have previously 
desiged a colour scheme for emacs that worked.  Opcodes are important and 
need to stand out.  Colouring the k in kvars differenty and then selecting 
the same colour as used for var (or damn close) is assinine.  The type 
belongs to the whole name.

But it is getting to time to cook

**Comment by nwhetsell** [comment]
@fsateler What I could do is add

```python
from pygments.lexers import _csound_builtins
```

and then add to the `OPCODES` set like

```python
_csound_builtins.OPCODES.add('missing_opcode')
```

**Comment by nwhetsell** [comment]
@jpffitch

> Then whoever designed them is hostile to the colour blind.

https://github.com/miikkas/lovelace

> For me not being to select usable colours is a huge backward step.

The only change I made to how colors are selected is to add a CSS file [here](https://github.com/nwhetsell/manual/blob/master/syntax-highlighting.css). Syntax highlighting of HTML files is applied using CSS currently, and it still will be if this is merged. Syntax highlighting of PDFs comes from [custom XSL](https://github.com/csound/manual/blob/master/xsl/customPDF.xsl.in) currently, and it [still will be](https://github.com/nwhetsell/manual/blob/master/xsl/customPDF.xsl.in) if this is merged. How colors are selected simply hasn’t changed.

> I have previously desig[n]ed a colour scheme for emacs that worked.

By all means share it.

> Opcodes are important and need to stand out.

OK.

> Colouring the k in kvars differenty and then selecting the same colour as used for var (or damn close) is assinine.

I disagree, but again, the colors are [here](https://github.com/nwhetsell/manual/blob/master/syntax-highlighting.css). The color for types has `Keyword.Type` next to it.

**Comment by nwhetsell** [comment]
@fsateler I added the opcodes that aren’t already in the `OPCODES` set in commit 6c64fbe1b7d57c298d6b73a314a4082439f81dd6.

**Comment by fsateler** [comment]
@nwhetsell Thanks! What I meant though is to read `opcodes_list.txt` directly:

```python
with open('opcodes_list.txt') as f:
    opcodeNames = f.readlines()

for opcodeName in opcodeNames:
    if opcodeName in _csound_builtins.OPCODES:
        print '_csound_builtins.OPCODES already contains ‘' + opcodeName + '’'
    else:
        _csound_builtins.OPCODES.add(opcodeName)
```

The idea would be that the script does not need editing for building the manual for a new version with new opcodes.

**Comment by nwhetsell** [comment]
@fsateler No problem. I’ll put back [opcode_list.txt](https://github.com/csound/manual/blob/master/opcode_list.txt) and use that if that’s preferred, but this may be a [“six of one, half a dozen of the other”](https://en.wiktionary.org/wiki/six_of_one,_half_a_dozen_of_the_other) situation. _Some_ file must be updated with new opcodes when distributing the manual for a new version of Csound. Whether that file is a script that does syntax highlighting or a separate text file may be unimportant. Also, I think there’s something to be said for having everything in one file, and opcode_list.txt is only read by [csd2docbook2.py](https://github.com/csound/manual/blob/master/csd2docbook2.py).

In commit 37e8978ab0279af10d719369ae53c904cbe2212d, I put the lists of opcodes in triple-quoted strings, one per line, like

```python
opcodeNames = '''
OSCinitM
S
⋮
tabifd
urandom
'''.split()
```

so there’s no real difference between adding opcodes to opcode_list.txt and adding opcodes to [csd2docbook.py](https://github.com/nwhetsell/manual/blob/master/csd2docbook.py). Will this work?

**Comment by fsateler** [comment]
@nwhetsell 

> Some file must be updated with new opcodes when distributing the manual for a new version of Csound

That's what I'm trying to avoid. I was under the impression that `opcodes_list.txt` was generated by invoking `csound -z`. But now that I think of it, it might make more sense to parse the `opcodes.xml` file directly and extract the `opcodename` from `csd2docbook.py`. What do others think?

FWIW, I think your solution is at least as good as the current status, so this is not a blocker.

However, the css color scheme should be changed to address @jpffitch comments. I have built the manual with your patches (as of d7f05ab), and put the output at https://sateler.com/tmp/html/, so that the code can be looked at with the actual background it will have.

**Comment by rorywalsh** [comment]
I think this is all good. I'm fine with the colour styling being changed to
suit John's comments. It's not a deal breaker for me. Like Steven, I would
rather variables are all the same colour, that is, the i, k, a etc, should
be the same colour as the letters that follow it. I'm not sure which is
better, parsing the output from "csound -z" or the opcodes.xml file. Is
there any difference really?

**Comment by gogins** [comment]
I'm afraid I find the previous coloring of the examples much easier to
read. Please, can we just create a style sheet that does the same things as
the old style sheet?

Regards,
Mike


-----------------------------------------------------
Michael Gogins
Irreducible Productions
http://michaelgogins.tumblr.com
Michael dot Gogins at gmail dot com

**Comment by nwhetsell** [comment]
> …it might make more sense to parse the opcodes.xml file directly and extract the opcodename from csd2docbook.py.

I’m not sure that will work because [opcodes.xml](https://github.com/csound/manual/blob/master/opcodes.xml) doesn’t contain all the opcodes in [opcode_list.txt](https://github.com/csound/manual/blob/master/opcode_list.txt). For example, it doesn’t contain opcodes with names beginning with `la_` or `mp3scal_`. Also, opcodes.xml is itself generated by [opcodeparser.py](https://github.com/csound/manual/blob/master/opcodeparser.py), so it probably shouldn’t be under version control anyway.

A possible issue with parsing output from `csound -z` is that its output may vary from system to system. For example, if STK opcodes are not present on a system, they won’t appear in the output of `csound -z`.

As for the colors, I’m happy to change them. I just need to know what to change them _to_.

As for type sigils, we needn’t highlight them. But, for what it’s worth, this is what [language-csound](https://atom.io/packages/language-csound) does in Atom. That package has been downloaded almost 300 times with no issues raised about highlighting type sigils, so either a few hundred people don’t like it and aren’t telling me, or some people prefer it that way.

**Comment by nwhetsell** [comment]
@gogins

> …can we just create a style sheet that does the same things as the old style sheet?

Sure, but there are some things that aren’t in the old stylesheet — strings, escaped characters, format specifiers — that now need colors because now they’re being lexed.

If there’s a preferred Emacs color scheme out there, I’d be happy to use it.

**Comment by nwhetsell** [comment]
Commit 7570601f0eb3c37b17fe13208df05edea9225bac uses styles and colors that match the current online manual. It also eliminates styling of type sigils.

To highlight strings, I used the color ([peru](https://www.w3.org/TR/css3-color/#peru)) that was used for double-slashed comments `//`. (Comments all get the same style and color in this fork.) Feel free to change the string color.

**Comment by kunstmusik** [comment]
@nwhetsell - I tried the latest and am getting green colors for sigils.  It's closer to what it was before; I am seeing two differences in expcurve:

* pfields (e.g., p3, p4) are colored blue now
* instr/endin is colored green now (was previously a purple color)

It's very nice to see strings being highlighted correctly now.

**Comment by nwhetsell** [comment]
Here’s what I see after running

```sh
make XSL_BASE_PATH=/usr/local/Cellar/docbook-xsl/1.79.1/docbook-xsl html
```

on a clean clone of my fork:

expcurve

p-fields, as built-in names, are now getting the style for built-in names. Please propose a specific change if you want something different.

**Comment by kunstmusik** [comment]
Looks like I just had to run csd2docbook.py here.  Odd, we have examples-xml in the top-level .gitignore, but we also have all the files in that folder checked into Git.  That doesn't really make sense and makes it error-prone to not check in updated examples-xml files, and running csd2docbook.py isn't a part of the build process.  

Anyways... I'm now getting the same results as you. The only difference I see between this and prior to this pull request is pfields being highlighted; I'm fine with that.  

If everyone else is okay with the change, the PR looks good to me now.  We do need to figure out what to do about examples-xml though.

**Comment by nwhetsell** [comment]
The only thing in the [top-level .gitignore](https://github.com/csound/manual/blob/master/.gitignore) here is “html”. I added examples-xml to the [top-level .gitignore of my fork](https://github.com/nwhetsell/manual/blob/master/.gitignore), and that change is part of this pull request, as is deleting the examples-xml folder in favor of generating that as a build step. (I believe I mentioned this in my original pull request.)

**Comment by kunstmusik** [comment]
Yes it is in your original text in PR, I missed it. But what I'm not seeing is "in favor of generating that as a build step." I see a Makefile target for examples-xml, but it is not called from elsewhere.  I think this is what caused me to see the older generated examples.  Shouldn't this be integrated somewhere, or am I missing something?

**Comment by nwhetsell** [comment]
It’s in `SRCS`: https://github.com/nwhetsell/manual/blob/master/Makefile#L685-L686.

**Comment by kunstmusik** [comment]
That doesn't seem to work here. You can test by deleting examples-xml/*.xml, then running "make html".  At least here, it does not trigger the examples-xml target.  I think the examples-xml folder is what is being looked at as a source, not the target.  If I rename the examples-xml target to examples-xml-build and do the same for the SRCS line, it does trigger the call to csd2docbook.py.

**Comment by nwhetsell** [comment]
That strikes me as expected. I can’t think of a reason to _directly_ change the contents of examples-xml once it’s generated. However, if you add to, delete from, or change a file in the [examples folder](https://github.com/csound/manual/tree/master/examples), or if you delete the examples-xml folder entirely, it will be regenerated.

**Comment by kunstmusik** [comment]
I see, I tried by reverting the Makefile change, touching one of the files in examples, then calling make which did re-run csd2docbook.py.  Actually, now when I rerun afterwards it's still re-running csd2docbook.py.  I have *no* idea why it did not trigger when I pulled that last commit.  

I'm good now to merge the PR.  I think colors are the only things people had issues over, so I'll go ahead an d merge.  If anyone else has issues, we can use a new issue to tackle it.

**Comment by gogins** [comment]
Looks good to me.

Best,
Mike

**Pull request merged**
