### PR TITLE
Update XML to DocBook 5, add TeX resources

### PR DESCRIPTION
**Pull request by nwhetsell**
This is a replacement of pull request #40 that applies the changes to a docbook5 branch rather than the master branch.

### CODE REVIEW

**Comment by vlazzarini** [comment]
OK, it's there, now people can try it out. If it works out for everyone, we'll merge it into the main branch.

**Comment by jpffitch** [comment]
So make does something, if slowly.  What I need as an occasional editor of 
the manual is a simple check list of what I have to do in a different way

**Comment by nwhetsell** [comment]
@jpffitch There’s more detail at pull request https://github.com/csound/manual/pull/40#issuecomment-157138142, but the short version is:

1. Use Unicode characters or numeric character references instead of named character references. For example, use a literal λ instead of `&lambda;`, and `&#xA0;` instead of `&nbsp;`. (You can still use [XML’s predefined entities](https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references#Predefined_entities_in_XML) like `&amp;` and `&lt;`.)

2. Use contributor names instead of entity references like `&namejohn;`.

3. Use XInclude elements like `<xi:include href="gettingstarted.xml"/>` instead of entity references like `&pfacegettingstarted;`.

4. If you add a new XML file, give it an XML declaration and a default namespace of `http://docbook.org/ns/docbook` with version 5.0, like this:
    
    ```xml
    <?xml version="1.0" encoding="UTF-8"?>
    <book xmlns="http://docbook.org/ns/docbook" version="5.0">
      <!-- More mark-up… -->
    </book>
    ```

**Comment by jpffitch** [comment]
On Tue, 17 Nov 2015, Nate Whetsell wrote:

> 
> @jpffitch There’s more detail at pull request #40 (comment), but the short
> version is:
>
>  1.
>
>     Use Unicode characters or numeric character references instead of named
>     character references. For example, use a literal λ instead of &lambda;,
>     and &#xA0; instead of &nbsp;. (You can still use XML’s predefined entities
>     like &amp; and &lt;.)

How do I fnd out (a) what Unicode characters are needed and (b) ow to type 
them?

>
>  2.
>
>     Use contributor names instead of entity references like &namejohn;.

This is a major backward step in consistncy.  I have however rescued a 
file of mappings fron &nameXXX; to text, but I still consider this very 
negatively
  >
>  3.
>
>     Use XInclude elements like <xi:include href="gettingstarted.xml"/> instead
>     of entity references like &pfacegettingstarted;.

No idea what this means

>
>  4.
>
>     If you add a new XML file, give it an XML declaration and a default
>     namespace of http://docbook.org/ns/docbook with version 5.0, like this:
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <book xmlns="http://docbook.org/ns/docbook" version="5.0">
>   
> </book>
>

Nor this

**Comment by nwhetsell** [comment]
> How do I fnd out (a) what Unicode characters are needed

I think most characters in the manual are going to be in the Latin and punctuation Unicode blocks; a few will be in the Greek block. There are many lists of Unicode characters available (like https://en.wikipedia.org/wiki/List_of_Unicode_characters), and one can look in the [code charts](http://www.unicode.org/charts/).

> and (b) ow to type them?

This depends on your OS. You can learn how to do this on OS&nbsp;X at https://support.apple.com/en-us/HT201586. [This](http://windows.microsoft.com/en-us/windows/using-special-characters-character-map-faq) is the top hit of a Google search for “windows insert special characters”. I’m afraid I haven’t used Linux in years.

> This is a major backward step in consistncy.  I have however rescued a file of mappings fron &nameXXX; to text, but I still consider this very negatively

My [goal](https://github.com/csound/manual/pull/40#issue-116966213) was “to increase the portability of the DocBook XML files”. Of course, there are trade-offs. I count 27 occurrences of the string “ ffitch” in the manual, and there are a few hundred uses of other contributor names, so eliminating the contributor name entities seemed like a reasonable trade-off, but perhaps not. If contributor name consistency is a priority, one way to do it without a DTD could be to use XML processing instructions, like `<?namejohn?>`, and replace those in an XSL transform.

>> Use XInclude elements like `<xi:include href="gettingstarted.xml"/>` instead of entity references like `&pfacegettingstarted;`.
>
> No idea what this means

XInclude elements can be used to include one XML document in another XML document. These are already used throughout the manual to include CSD files; [opcodes/template.xml contains one](https://github.com/csound/manual/blob/master/opcodes/template.xml#L123). Since I removed entities defining XML files, XInclude elements should be used instead. For an example, compare [manual/preface/top.xml](https://github.com/csound/manual/blob/master/preface/top.xml) to [docbook5/preface/top.xml](https://github.com/csound/manual/blob/docbook5/preface/top.xml).

>> If you add a new XML file, give it an XML declaration and a default namespace of `http://docbook.org/ns/docbook` with version 5.0…
>
> Nor this

The [opcode template in the master branch](https://github.com/csound/manual/blob/master/opcodes/template.xml) looks like this:

```xml
<refentry id="newopcodename">
  <!-- More mark-up… -->
</refentry>
```

The [opcode template in the docbook5 branch](https://github.com/csound/manual/blob/docbook5/opcodes/template.xml) looks like this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<refentry xmlns="http://docbook.org/ns/docbook" version="5.0" id="newopcodename">
  <!-- More mark-up… -->
</refentry>
```

The template in the docbook5 branch starts with an XML declaration `<?xml version="1.0" encoding="UTF-8"?>`, and the root `<refentry>` element has attributes for the DocBook namespace and its version. Other new XML files in the docbook5 branch should follow suit.

As a new contributor, I’m not comfortable pushing further for these changes. Thanks for your consideration, and sorry for the trouble.

**Pull request merged**
