### PR TITLE
Build with python3

### PR DESCRIPTION
**Pull request by fsateler**
Python2 is EOL since last year.

### CODE REVIEW

**Comment by jpffitch** [comment]
Any idea why the CI builds failed?  I am guessing that the PR code does not change the yaml files so it is trying to run it with python2 but I am not a python user so rely on someone else.

**Comment by jpffitch** [comment]
I do not think this PR is correct/complete.  It changed python calls to python3 calls in the Makefile, and some other change to yaml.

If I change the Makefile locally it dos not build the manual
```
  File "quickref.py", line 57
    print file_to_add
                    ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(file_to_add)?
make: *** [Makefile:721: html-dist] Error 1
```

**Comment by fggp** [comment]
The error happens because quickref.py can only be run under Python 2 as it is. It has to be adapted for Python 3. I'll have a look as soon as I can.

**Comment by fggp** [comment]
I modified opcodeparser.py and quickref.py for Python3. There's still some work to do for makeframes.py

**Comment by fggp** [comment]
For the moment I will comment out the line calling makeframes.py in Makefile

**Pull request closed without merging**
