### PR TITLE
 Make csd2docbook.py work with Pygments 2.3

### PR DESCRIPTION
**Pull request by nwhetsell**
This pull request makes csd2docbook.py work with Pygments 2.3. It also includes a minor simplification of the instructions for installing DocBook on macOS.

The build is passing on Travis CI and AppVeyor:

[Build Status](https://travis-ci.org/nwhetsell/manual) [Build status](https://ci.appveyor.com/project/nwhetsell/manual)

### CODE REVIEW

**Comment by nwhetsell** [comment]
> Is this comparable with current code?

Visit https://github.com/csound/manual/pull/143/files to view a file-by-file comparison.

> That is will it work with my working system?

 I don’t know anything about your system, so I can’t answer this.

**Comment by kunstmusik** [comment]
Thanks @nwhetsell !  

I tested the PR code by:

1. upgraded my install of pygments using ```pip install pygments --upgrade``` which installed 2.3.1
2. ran make html-dist

csd2docbook.py ran here.  It ran with the older version of pygments too, which I think means the updated csd2docbook.py would produce an incorrect output if an end user is using an older version of pygments (i.e. missing sections that used to be manually added prior to 2.3).  

I did run into an issue running html-dist:

```
python makeframes.py
--------Title:
Traceback (most recent call last):
  File "makeframes.py", line 196, in <module>
    print "--------Title:", sections[j].childNodes[1].firstChild.toxml().encode('utf-8')
IndexError: list index out of range
```

This is all tested on Windows 10 using MSYS2.  I'll try using Ubuntu on Windows Subsystem for Linux next.  

Additionally, I saw that travis is using ```make html pdf``` where we might want to change to ```make html-dist pdf```.

**Comment by nwhetsell** [comment]
@kunstmusik From a [POLA](https://en.wikipedia.org/wiki/Principle_of_least_astonishment) standpoint, having csd2docbook.py run with Pygments 2.1–2.2 strikes me as better than running with only the latest version of Pygments. Also, I’m not sure what you mean by “missing sections that used to be manually added prior to 2.3”; csd2docbook.py doesn’t add sections. It simply converts CSD files in [examples](https://github.com/csound/manual/tree/master/examples) to XML files in examples-xml. The effect of [removing opcode names that are included in Pygments 2.3 and later](https://github.com/csound/manual/pull/143/commits/890700cd40d42dc6b1f20448c07168aad92a7296) is that the removed opcodes won’t be highlighted as built-in names with Pygments 2.1–2.2. The Csound lexers in Pygments 2.1–2.2 also don’t highlight [`A4`](https://csound.com/docs/manual/A4.html), don’t highlight [`d`](https://csound.com/docs/manual/d.html), don’t do a very good job at highlighting [format specifiers in strings](https://csound.com/docs/manual/printks.html), and have some issues with highlighting [preprocessor directives](https://csound.com/docs/manual/include.html). The solution to all this is to simply use Pygments 2.3 or later. A version-check of Pygments seems out-of-scope for this pull request, but I believe this can be accomplished by importing `pygments` and checking [`pygments.__version__`](https://bitbucket.org/birkenfeld/pygments-main/src/23886cb7f295543c91bf11ebd70fba56ac1ea9dc/pygments/__init__.py#__init__.py-32).

I believe the error from makeframes.py is unrelated to this pull request. I’ve updated CI files to build the html-dist target, and both [Travis CI](https://travis-ci.org/nwhetsell/manual/jobs/473823892#L5126) and [AppVeyor](https://ci.appveyor.com/project/nwhetsell/manual/builds/21304995#L4661) run makeframes.py without incident. The line that results in an error—

https://github.com/csound/manual/blob/be7a9afa390c0ef14a6162ce75f5860e53ec8e04/makeframes.py#L196

—prints something about the second child node of the “section” at index `j`. The `sections` list consists of the `span` elements in the `toc`:

https://github.com/csound/manual/blob/be7a9afa390c0ef14a6162ce75f5860e53ec8e04/makeframes.py#L170-L171

The `toc` is a particular element in `indexparse`:

https://github.com/csound/manual/blob/be7a9afa390c0ef14a6162ce75f5860e53ec8e04/makeframes.py#L159

And `indexparse` is the contents of html/index.html:

https://github.com/csound/manual/blob/be7a9afa390c0ef14a6162ce75f5860e53ec8e04/makeframes.py#L19-L22

However, csd2docbook.py neither writes nor reads html/index.html. If I had to take a wild guess, I’d say that there’s a `span` element in your `toc` that has fewer than two child nodes. (Incidentally, the brittleness of the makeframes.py script is what prompted me to rewrite it as [makeframes.xsl](https://github.com/csound/manual/blob/docbook5/makeframes.xsl) several years ago.)

**Comment by kunstmusik** [comment]
My mistake about "sections", yes it's just what gets highlighted.  

I also just ran this on Ubuntu using the latest pygments. All ran well, and not sure what caused it to fail on MSYS2 but will move on. Going to merge pull request, thanks @nwhetsell for this.

As for makeframes.xsl, I haven't looked at this code nor have time to investigate further.  Thanks for the writeup to explain the issue.  Perhaps moving to makeframes.xsl would be good for the future.

**Comment by nwhetsell** [comment]
@kunstmusik Thanks, it may also be a good idea to [add csound/manual to AppVeyor](https://www.appveyor.com/docs/) so that continuous integration on Windows actually runs. (There’s been an appveyor.yml file here [for over a year](https://github.com/csound/manual/pull/118).)

**Comment by kunstmusik** [comment]
@nwhetsell I suppose that message about enabling on Appveyor slipped through. I went and added it to appveyor to build and used the same notifications to Slack and Email as the main csound project:

https://ci.appveyor.com/project/csound/manual/

I kicked off a build, we should be getting messages on csound-dev as well as #dev-alerts on Slack now.

**Pull request merged**
