### PR TITLE
Updating #ifdef example

### PR DESCRIPTION
**Pull request by tgrey1**
After some discussion and work with Menno, we arrived at this more detailed #ifdef example.

### CODE REVIEW

**Comment by tgrey1** [comment]
This was shamelessly copy-pasted from another opcode's example section (oscil, to be precise).

I'm honestly not sure if this part is needed or should even be there:
<para>See the sections <link linkend="UsingRealTime"><citetitle>Real-time Audio</citetitle></link> and <link linkend="CommandFlags"><citetitle>Command Line Flags</citetitle></link> for more information on using command line flags.</para>

But other than that it should be a good starting point for a more detailed example of ifdef

**Comment by jpffitch** [comment]
#ifdef is a preprocessor opcode

**Comment by tgrey1** [comment]
Yeah, oops.  I realized I shouldn't have called it an opcode and added https://github.com/csound/manual/pull/195/commits/7af599fe51a8ed712f4ab71807f09afe1536c254 at the last minute.  It's modeled after the wording that was already there.

**Comment by tgrey1** [comment]
@tjingboem - adding you, since you've been helping here too.

**Pull request merged**
